package com.capgemini.training;

	import java.util.Scanner;

	public class Test {
	    public static void main(String[] args) {
	    	//TODO Autogenerated method stub
	        Scanner sc = new Scanner(System.in);
	        System.out.println("Please Enter no of Tickets Available:");
	        int noOfTicketAvail=sc.nextInt();
	        System.out.println("Please Enter Ticket Price:");
	        int ticketPrice = sc.nextInt();
	        System.out.println("Please Enter No Tickets Needed:");
	        int noOfTicketRequested = sc.nextInt();
	        com.capgemini.training.TicketMachine TM = new com.capgemini.training.TicketMachine(ticketPrice ,noOfTicketAvail);
	        if(TM.checkTicketsAvailability(noOfTicketAvail, noOfTicketRequested)==false) {
	            System.out.println("noOfTicketRequested is more than TicketAvailability");
	            System.exit(0);
	        }
	        else {
	            TM.printTicket();
	        }
	    }
	}

